services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: rally
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
  mail:
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
